config/routes.rb
Todo::Application.routes.draw do
  resources :todo_lists

  resources :users

  root :to => "todo_lists#index"

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  attr_accessible :description, :due_date, :title

  validates_presence_of :title

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email

  validates_presence_of :email, :on => :create
  validates_uniqueness_of :email, :message => "must be unique"

   has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
	respond_to :html, :xml, :js

	def index
		respond_with(@todo_lists = TodoList.all)
	end

	def new
    @todo_lists = TodoList.new
  end
  
  def show
    @todo_list = TodoList.find(params[:id])
  end

  def create
    @todo_list = TodoList.new(params[:todo_list])
    if @todo_list.save
      flash[:notice] = "New TodoList succesfully created."
      respond_with(@todo_list, :location => todo_list_url(@todo_list))
    else
      flash[:error] = "Sorry you missing a title"
      redirect_to new_todo_list_url
    end
  end
  
  def edit
    @todo_list = TodoList.find(params[:id])
  end
  
  def update
    @todo_list = TodoList.find(params[:id])
    if @todo_list.update_attributes(params[:todo_list])
      flash[:notice] = "TodoList is succesfully updated."
      respond_with(@todo_list, :location => todo_list_url(@todo_list))
    else
      flash[:error] = "Sorry you missing a title"
      redirect_to edit_todo_list_path(@todo_list)
    end
  end
  
  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy
    flash[:notice] = "TodoList is finished great continue that way"
    redirect_to todo_list_url
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :html, :xml, :js

	def index
		@user = User.new
		@user = User.where(params[:user])
		# if @user.present?
		# 	respond_with(@users, :location => todo_lists_url)
		# else
		# 	flash[:error] = "sorry email doesnt exist in the system"
		# 	redirect_to user_url
		# end
	end

	def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "New user succesfully created."
      respond_with(@user, :location => todo_lists_url)
    else
      flash[:error] = "Sorry you email is not correct"
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_lists/edit.html.erb
<h1>Edit your todo</h1>

<%= form_for @todo_list do |form| %>
	
	<label>Title:
		<p><%= form.text_field :title %></p>
	</label>
	
	<label>Description:
		<p><%= form.text_field :description %></p>
	</label>

	<label>Due date:
		<p><%= form.text_field :due_date %></p>
	</label>
	
	<p><%= form.submit %></p>
	
<% end %>

app/views/todo_lists/index.html.erb
<h1>Todo list</h1>

<% @todo_lists.each do |t| %>
	<h3><%= t.title%>- <%= link_to "Edit", edit_todo_list_url(t) %> | <%= link_to "Finish", todo_list_url(t), :method => :delete %></h3>
	<br />
<%end%>

<%= link_to "Create todo", new_todo_list_url %>

app/views/todo_lists/new.html.erb
<h1>Create a new todo </h1>

<%= form_for @todo_lists do |form| %>
	
	<label>Title:
		<p><%= form.text_field :title %></p>
	</label>
	
	<label>Description:
		<p><%= form.text_field :description %></p>
	</label>

	<label>Due date:
		<p><%= form.text_field :due_date %></p>
	</label>
	
	<p><%= form.submit %></p>
	
<% end %>

app/views/todo_lists/show.html.erb
<h2><%= @todo_list.title %></h2>
<p><%= @todo_list.description %></p>
<p><%= @todo_list.due_date %></p>

<%= link_to "All to do lists", todo_lists_url %>

app/views/users/index.html.erb
<h1>Welcome to todo list application</h1>

<%= form_for @user do |form| %>
	
	<label>please enter your email :
		<p><%= form.text_field :email %></p>
	</label>
	
	<p><%= form.submit %></p>
	<%= link_to "Create new user", new_user_url %>
	
<% end %>